# Generated by Django 5.1.4 on 2025-03-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('domain_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('domain_name', models.CharField(max_length=128, unique=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=128, null=True)),
                ('state', models.CharField(blank=True, max_length=128, null=True)),
                ('city', models.CharField(blank=True, max_length=128, null=True)),
                ('latitude', models.CharField(blank=True, max_length=128, null=True)),
                ('longitude', models.CharField(blank=True, max_length=128, null=True)),
                ('isp', models.CharField(blank=True, max_length=128, null=True)),
                ('open_ports', models.CharField(blank=True, max_length=128, null=True)),
                ('asn', models.CharField(blank=True, max_length=128, null=True)),
                ('ip_version', models.CharField(blank=True, choices=[('IPv4', 'IPv4'), ('IPv6', 'IPv6')], max_length=128, null=True)),
                ('status', models.CharField(choices=[('Domain Added', 'Domain Added'), ('Domain Scanning InProgress', 'Domain Scanning InProgress'), ('Domain Scanning Completed', 'Domain Scanning Completed')], default='Domain Added', max_length=128)),
            ],
        ),
    ]
