# Generated by Django 5.1.4 on 2025-03-10 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domain',
            old_name='asn',
            new_name='domain_asn',
        ),
        migrations.RenameField(
            model_name='domain',
            old_name='city',
            new_name='domain_city',
        ),
        migrations.RenameField(
            model_name='domain',
            old_name='country',
            new_name='domain_country',
        ),
        migrations.RenameField(
            model_name='domain',
            old_name='ip',
            new_name='domain_ip',
        ),
        migrations.RenameField(
            model_name='domain',
            old_name='isp',
            new_name='domain_isp',
        ),
        migrations.RenameField(
            model_name='domain',
            old_name='latitude',
            new_name='domain_latitude',
        ),
        migrations.RenameField(
            model_name='domain',
            old_name='longitude',
            new_name='domain_longitude',
        ),
        migrations.RenameField(
            model_name='domain',
            old_name='open_ports',
            new_name='domain_open_ports',
        ),
        migrations.RenameField(
            model_name='domain',
            old_name='state',
            new_name='domain_state',
        ),
        migrations.RenameField(
            model_name='domain',
            old_name='status',
            new_name='domain_status',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='ip_version',
        ),
        migrations.AddField(
            model_name='domain',
            name='domain_ip_version',
            field=models.CharField(blank=True, choices=[('NA', 'NA'), ('IPv4', 'IPv4'), ('IPv6', 'IPv6')], max_length=128, null=True),
        ),
        migrations.CreateModel(
            name='SubDomain',
            fields=[
                ('subdomain_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('subdomain_name', models.CharField(max_length=128, unique=True)),
                ('sub_domain_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('sub_domain_country', models.CharField(blank=True, max_length=128, null=True)),
                ('sub_domain_state', models.CharField(blank=True, max_length=128, null=True)),
                ('sub_domain_city', models.CharField(blank=True, max_length=128, null=True)),
                ('sub_domain_latitude', models.CharField(blank=True, max_length=128, null=True)),
                ('sub_domain_longitude', models.CharField(blank=True, max_length=128, null=True)),
                ('sub_domain_isp', models.CharField(blank=True, max_length=128, null=True)),
                ('sub_domain_open_ports', models.CharField(blank=True, max_length=128, null=True)),
                ('sub_domain_asn', models.CharField(blank=True, max_length=128, null=True)),
                ('sub_domain_ip_version', models.CharField(blank=True, choices=[('NA', 'NA'), ('IPv4', 'IPv4'), ('IPv6', 'IPv6')], max_length=128, null=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='base.domain')),
            ],
        ),
    ]
