# Generated by Django 5.1.4 on 2025-03-10 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_asn_domain_domain_asn_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subdomain',
            old_name='sub_domain_asn',
            new_name='subdomain_asn',
        ),
        migrations.RenameField(
            model_name='subdomain',
            old_name='sub_domain_city',
            new_name='subdomain_city',
        ),
        migrations.RenameField(
            model_name='subdomain',
            old_name='sub_domain_country',
            new_name='subdomain_country',
        ),
        migrations.RenameField(
            model_name='subdomain',
            old_name='sub_domain_ip',
            new_name='subdomain_ip',
        ),
        migrations.RenameField(
            model_name='subdomain',
            old_name='sub_domain_ip_version',
            new_name='subdomain_ip_version',
        ),
        migrations.RenameField(
            model_name='subdomain',
            old_name='sub_domain_isp',
            new_name='subdomain_isp',
        ),
        migrations.RenameField(
            model_name='subdomain',
            old_name='sub_domain_latitude',
            new_name='subdomain_latitude',
        ),
        migrations.RenameField(
            model_name='subdomain',
            old_name='sub_domain_longitude',
            new_name='subdomain_longitude',
        ),
        migrations.RenameField(
            model_name='subdomain',
            old_name='sub_domain_open_ports',
            new_name='subdomain_open_ports',
        ),
        migrations.RenameField(
            model_name='subdomain',
            old_name='sub_domain_state',
            new_name='subdomain_state',
        ),
    ]
