# Generated by Django 5.1.4 on 2025-03-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_sub_domain_asn_subdomain_subdomain_asn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdomain',
            name='subdomain_ip_version',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
