# Generated by Django 5.1.4 on 2025-03-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_subdomain_subdomain_ip_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pending_Meta',
            fields=[
                ('Pending_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('Ip', models.GenericIPAddressField()),
                ('Send_status', models.BooleanField(default=False)),
                ('Meta_id', models.IntegerField(blank=True, null=True)),
                ('Meta_start_time', models.DateTimeField(blank=True, null=True)),
                ('Meta_stop_time', models.DateTimeField(blank=True, null=True)),
                ('Meta_scan_status', models.CharField(choices=[('-1', 'Meta Scan Aborted'), ('0', 'Pending Meta Scan'), ('1', 'Sent To Meta'), ('2', 'Meta Scanning'), ('3', 'Meta Completed ')], default='0', max_length=30)),
            ],
            options={
                'ordering': ['Pending_id'],
            },
        ),
    ]
