# Generated by Django 5.1.4 on 2025-03-12 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_pending_meta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pending_Meta',
        ),
    ]
