# Generated by Django 5.1.4 on 2025-03-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_delete_pending_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='domain_add_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='domain_scan_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='domain_scan_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
