# Generated by Django 5.1.4 on 2025-03-19 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_domain_domain_add_time_domain_domain_scan_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='priority',
            field=models.CharField(choices=[('2', 'Very High Priority'), ('1', 'High Priority'), ('0', 'Normal')], default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='domain',
            name='domain_add_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
