# Generated by Django 5.1.4 on 2025-03-19 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='scan_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
