# Generated by Django 5.1.4 on 2025-03-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_config_scan_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='scan_count',
            field=models.PositiveIntegerField(default=0, help_text='The current scan count of the domains in queue.'),
        ),
    ]
