# Generated by Django 5.1.4 on 2025-03-24 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_show'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Show',
        ),
    ]
