# Generated by Django 5.1.4 on 2025-04-09 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_domain_domain_result_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='domain_abort_reason',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='domain_status',
            field=models.CharField(choices=[('Domain Added', 'Domain Added'), ('Domain Scanning InProgress', 'Domain Scanning InProgress'), ('Domain ip found successfully', 'Domain ip found successfully'), ('Domain Scanning Completed', 'Domain Scanning Completed')], default='Domain Added', max_length=128),
        ),
    ]
