# Generated by Django 5.1.4 on 2025-04-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_domain_domain_abort_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='domain_status',
            field=models.CharField(choices=[('Domain Added', 'Domain Added'), ('Domain Scanning InProgress', 'Domain Scanning InProgress'), ('Domain ip found successfully', 'Domain ip found successfully'), ('Domain Scanning Completed', 'Domain Scanning Completed'), ('Domain Scanning Aborted', 'Domain Scanning Aborted')], default='Domain Added', max_length=128),
        ),
    ]
