# Generated by Django 5.1.4 on 2025-04-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_domain_domain_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='subdomain_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='domain_status',
            field=models.CharField(choices=[('Domain Added', 'Domain Added'), ('Domain Scanning InProgress', 'Domain Scanning InProgress'), ('Domain ip found successfully', 'Domain ip found successfully'), ('Geolocation Scan Completed successfully', 'Geolocation Scan Completed successfully'), ('Domain Scanning Completed', 'Domain Scanning Completed'), ('Domain Scanning Aborted', 'Domain Scanning Aborted')], default='Domain Added', max_length=128),
        ),
    ]
