# Generated by Django 5.1.4 on 2025-04-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_domain_subdomain_count_alter_domain_domain_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='domain_status',
            field=models.CharField(choices=[('Domain Added', 'Domain Added'), ('Domain Scanning InProgress', 'Domain Scanning InProgress'), ('Domain ip found', 'Domain ip found'), ('Geolocation Scan Completed', 'Geolocation Scan Completed'), ('Nmap Scan Completed', 'Nmap Scan Completed'), ('SubFinder Scan Completed', 'SubFinder Scan Completed'), ('Domain Scanning Completed', 'Domain Scanning Completed'), ('Domain Scanning Aborted', 'Domain Scanning Aborted')], default='Domain Added', max_length=128),
        ),
    ]
